[project]
name = "opengl-tag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maxwell Aguiar Silva", email = "maxwellaguiarsilva@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
opengl-tag = "opengl_tag:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
