#!/bin/bash

if [ "$#" -eq 0 ]; then
    PYTHONPATH=tools tools/llm/statistic.py
else
    JSON_NAMES="["
    for arg in "$@"; do
        JSON_NAMES="${JSON_NAMES}\"${arg}\","
    done
    JSON_NAMES="${JSON_NAMES%,}]"

    PYTHONPATH=tools tools/llm/statistic.py "$( cat <<-EOF
{ "name": ${JSON_NAMES} }
EOF
)"
fi