#!/bin/bash


if [ "$#" -eq 0 ]; then
    MCP_CALL_LOCK=1 PYTHONPATH=tools tools/llm/statistic.py "{}"
else
    JSON_NAMES="["
    for arg in "$@"; do
        JSON_NAMES="${JSON_NAMES}\"${arg}\","
    done
    JSON_NAMES="${JSON_NAMES%,}]"

    MCP_CALL_LOCK=1 PYTHONPATH=tools tools/llm/statistic.py "$( cat <<-EOF
{ "name": ${JSON_NAMES} }
EOF
)"
fi


