#!/usr/bin/python


import sys
import subprocess
import datetime
import time
from template_module import template


def get_git_config_value( configuration_name ):
    try:
        command = [ "git", "config", "--global", configuration_name ]
        process = subprocess.run( command, capture_output=True, text=True, check=True )
        return  process.stdout.strip( )
    except subprocess.CalledProcessError:
        return  "value not found"

def	create_class( class_hierarchy : str, output_directory: str ):
    model = template( "class" )
    hierarchy_list=class_hierarchy.split( "/" )
    file_path = f"{output_directory}/{'/'.join( hierarchy_list )}.hpp"
    result = model.run( {
         "num_year": datetime.datetime.now( ).strftime( "%Y" )
        ,"des_full_name": get_git_config_value( "user.name" )
        ,"des_email": get_git_config_value( "user.email" )
        ,"des_formatted_datetime": datetime.datetime.now( ).strftime( "%Y-%m-%d %H:%M" )
        ,"des_file_path": "/".join( hierarchy_list ) + ".hpp"
        ,"class_name": hierarchy_list[-1]
        ,"namespace_list": hierarchy_list[:-1]
        ,"include_list": [ "string", "sak.hpp" ]
        ,"using_list": [ "::std::string" ]
        ,"header_guard": f"hpp{ str( time.time_ns( ) )[-9:] }"
    } )
    # Ensure the directory exists before writing the file
    subprocess.run( [ "mkdir", "-p", "/".join( file_path.split( "/" )[:-1] ) ] )
    with open( file_path, "w" ) as f:
        f.write( result )
    return  file_path




if __name__ == "__main__":
       output_dir = "include"
       created_file = create_class( sys.argv[ 1 ], output_dir )
       print( f"Created file: {created_file}" )



