#!/usr/bin/python


import re

r_import        =   r"\{\{import\s+([a-zA-Z0-9_-]+)\}\}"
r_list_open     =   r"\{\{list_open\s+([a-zA-Z0-9_-]+)\}\}"
r_list_close    =   r"\{\{list_close\s+([a-zA-Z0-9_-]+)\}\}"
r_list_item     =   r"\{\{list_item\s+([a-zA-Z0-9_-]+)\}\}"

class template:
    def __init__( self, name, path = "docs/templates" ):
        assert( self != "" )
        self.path = path
        self.text = self.load( name )
    
    def load( self, name ):
        with open( f"{self.path}/{name}.txt", "r" ) as file:
            text = file.read( )
        text = re.sub( r_import, lambda match: self.load( match.group( 1 ) ), text )
        return  text
    
    def run( self, data: dict ) -> str:
        text = self.text
        for key, value in data.items( ):
            if isinstance( value, str ):
                text = text.replace( f"{{{{{key}}}}}", str( value ) )
            elif isinstance( value, list ):
                r_key = (
                        r"\{\{list_open\s+"
                    +   re.escape( key )
                    +   r"\}\}(.*?)\{\{list_close\s+"
                    +   re.escape( key )
                    +   r"\}\}"
                )
                r_item = (
                        r"\{\{list_item\s+"
                    +   re.escape( key )
                    +   r"\}\}"
                )
                text = re.sub(
                     r_key
                    ,lambda match: "".join( [ re.sub( r_item, item, match.group( 1 ) ) for item in value ] )
                    ,text
                    ,flags = re.DOTALL
                )
        return  text
    


#   just a test to see if it works
import subprocess
import datetime
import time
def get_git_config_value( configuration_name ):
    try:
        command = [ "git", "config", "--global", configuration_name ]
        process = subprocess.run( command, capture_output=True, text=True, check=True )
        return  process.stdout.strip( )
    except subprocess.CalledProcessError:
        return  "value not found"

model = template( "class" )
hierarchy_list="tui/screen".split( "/" )
data = {
     "num_year": datetime.datetime.now( ).strftime( "%Y" )
    ,"des_full_name": get_git_config_value( "user.name" )
    ,"des_email": get_git_config_value( "user.email" )
    ,"des_formatted_datetime": datetime.datetime.now( ).strftime( "%Y-%m-%d %H:%M" )
    ,"des_file_path": "/".join( hierarchy_list ) + ".hpp"
    ,"class_name": hierarchy_list[-1]
    ,"namespace_list": hierarchy_list[:-1]
    ,"include_list": [ "string", "ncurses.h" ]
    ,"using_list": [ "::std::string" ]
    ,"header_guard": f"hpp{ str( time.time_ns( ) )[-9:] }"
}

result = model.run( data )
print( result )


