#!/bin/bash


declare -A project
declare -A folders
declare -a lib_list

project[cpp_version]="${project[cpp_version]:-"c++23"}"
project[file_extension]="${file_extension:-"cpp"}"
project[file_filter]="${project[file_filter]:-"*.${project[file_extension]}"}"
project[main_regexp]="${project[main_regexp]:-"\\bint\\s+main\\s*\\("}"
folders[source]="${folders[source]:-"source"}"
folders[include]="${folders[include]:-"include"}"
folders[tests]="${folders[tests]:-"tests"}"
folders[build]="${folders[build]:-"build"}"
folders[dist]="${folders[dist]:-"dist"}"

lib_list+=( "-lncurses" )


build_cpp_file( )
{
	local -A files
	files[cpp]="${1#./}"
	files[obj]="${folders[build]}/${files[cpp]%.*}.o"
	files[dep]="${files[obj]}.d"

	if [[ ! -f "${files[obj]}" || "${files[cpp]}" -nt "${files[obj]}" ]];
	then
		echo "build: ${files[cpp]}"
		mkdir -p "$( dirname "${files[obj]}" )"
		g++ -m64 -c -Wfatal-errors -Werror -MMD -MP -std="${project[cpp_version]}"	\
			-I"${folders[include]}"	\
			-MF "${files[dep]}"		\
			-o "${files[obj]}"		\
			"${files[cpp]}"	|| return "${?}"
	fi
}


remove_orphaned_object( )
{
	local cpp_path
	cpp_path="$( echo "${1%.o}" | cut -d'/' -f3- ).${project[file_extension]}"
	if [[ ! -f "${cpp_path}" ]];
	then
		rm -rf "$1" "$1.d"
		echo "removido: $1"
	fi
}

build_binary( )
{
	local -a link_list
	local -A files
	local main_file
	
	link_list=()
	main_file="${1}"
	files[main]="${main_file#./}"
	files[bin]="${folders[dist]}/$( basename "${files[main]%.*}" )"

	while read -r "cpp_file"
	do
		files[cpp]="${cpp_file#./}"
		files[obj]="${folders[build]}/${files[cpp]%.*}.o"

		grep -qE "${project[main_regexp]}" "${files[cpp]}" && continue	#	ignore main files
		[[ "${files[main]}" == "${folders[source]}"* ]] && \
			[[ "${files[cpp]}" == "${folders[tests]}"* ]] && continue	#	if is not a test then ignore test folder
		[[ "${files[cpp]}" == "${folders[tests]}"* ]] && \
			[[ "${files[cpp]}" != "${files[main]%/*}"* ]] && continue	#	if is a test then ignore files from another main test

		link_list+=( "${files[obj]}" )
	done <<< "$( find . -name "${project[file_filter]}" -type f )"
	
	echo "________________________________________________________________________________"
	echo "${files[bin]} from ${files[main]}"
	for obj_file in "${link_list[@]}"; do echo -e "\t${obj_file}"; done

	g++ -m64 -o "${files[bin]}" "${folders[build]}/${files[main]%.*}.o" "${link_list[@]}" "${lib_list[@]}" || exit 1
}


build_project( )
{
	mkdir -p "${folders[build]}" "${folders[dist]}"
	while read -r line; do build_cpp_file "$line" || return "${?}"; done <<< "$( find . -name "${project[file_filter]}" )"
	while read -r line; do build_binary "$line"; done <<< "$( find . -name "${project[file_filter]}" -type f -exec grep -lE "${project[main_regexp]}" {} \; )"
	while read -r line; do remove_orphaned_object "$line"; done <<< "$( find . -name "*.o" )"
}

build_project


