#!/usr/bin/python3


config    =    {
     "cpp_version": "c++23"
    ,"file_extension": "cpp"
    ,"file_filter": "*.cpp"
    ,"main_regexp": r"\b(int|auto)\s+main\s*\(",
    ,"folders": {
         "source": "source"
        ,"include": "include"
        ,"tests": "tests"
        ,"build": "build"
        ,"dist": "dist"
    }
}

#   preencha as listas abaixo com o path dos arquivos
#   as pastas devem ser as que estão no dict `config`
include_list    =   [ ] #   todos hpp da pasta include
source_list     =   [ ] #   todos cpp da pasta source
tests_list      =   [ ] #   todos cpp da pasta tests



